scrape_configs:
  - job_name: 'fastapi-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']





#docker run -d -p 9090:9090 --name prometheus_container -v "C:/Users/Sourabh Kumar Das/Desktop/assigment_1/fastapi_application/prometheus.yml:/etc/prometheus/prometheus.yml" prom/prometheus

# docker run -d -p 9090:9090 --name prometheus_container -v prometheus_data:/etc/prometheus -v "C:/Users/Sourabh Kumar Das/Desktop/assigment_1/fastapi_application/prometheus.yml:/etc/prometheus/prometheus.yml"  prom/prometheus
