name: fast_api

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        options: --health-cmd="curl --silent --fail localhost:27017" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 . --max-line-length=88

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q
