name: FastAPI with MongoDB CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0  # You can specify a version like mongo:5.0 for stability
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Define all your environment variables here
      DATABASE_URL: mongodb://mongo_db:27017/   # Use docker service name as URL
      DB_NAME: fast_api_db
      SECRET_KEY: "bGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
      ALGORITHM: "HS256"
      TEST_DATABASE_URL: mongodb://mongo_db:27017/   # Use docker service name for tests
      TEST_DB_NAME: fastapi_test_db

      # Docker specific values
      DATABASE_URL_DOCKER: mongodb://mongo_db:27017/
      DB_NAME_DOCKER: fast_api_db
      TEST_DATABASE_URL_DOCKER: mongodb://mongo_db:27017/
      TEST_DB_NAME_DOCKER: fastapi_test_db

      # If you use GitHub secrets for MONGODB_URI_SECRET, ensure it's set properly
      # MONGODB_URI: ${{ secrets.MONGODB_URI_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
