name: CI Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

      
jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        options: >-
          --health-cmd="mongo --eval 'db.stats()'"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10
        ports:
          - 27017:27017

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 . --max-line-length=79

    - name: Wait for MongoDB to initialize
      run: |
        echo "Waiting for MongoDB to initialize..."
        sleep 30

    - name: Wait for MongoDB to start
      run: |
        echo "Waiting for MongoDB to start..."
        for i in {1..30}; do
          if mongo --eval 'db.stats()' > /dev/null 2>&1; then
            echo "MongoDB is ready!"
            break
          fi
          echo "MongoDB not ready, waiting 2 seconds..."
          sleep 2
        done

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q